export const ourWorkList = [
  {
    id: '1',
    img: '/portfolio.png',
    url: 'https://webpetto.dhicta2upu5zd.amplifyapp.com',
    title: 'Brick & Stone',
    type: '랜딩페이지',
    duration: '12일 (기획 2일 / 디자인 4일 / 퍼블리싱 6일)',
    keywords: '#개성있는 #통통튀는 #깔끔한',
    color: '',
    purpose: 'asd',
  },
  {
    id: '2',
    img: '/portfolio.png',
    url: 'https://webpetto.d2xngy89xbu3gc.amplifyapp.com',
    title: 'Officia',
    type: '랜딩페이지',
    duration: '12일 (기획 2일 / 디자인 4일 / 퍼블리싱 6일)',
    keywords: '#개성있는 #통통튀는 #깔끔한',
    color: '',
    purpose: 'asd',
  },
  {
    id: '3',
    img: '/portfolio.png',
    url: 'https://webpetto.d2cpkqwx3bl9jj.amplifyapp.com',
    title: "Titan's Note",
    type: '랜딩페이지',
    duration: '12일 (기획 2일 / 디자인 4일 / 퍼블리싱 6일)',
    keywords: '#개성있는 #통통튀는 #깔끔한',
    color: '',
    purpose: 'asd',
  },
  {
    id: '4',
    img: '/portfolio.png',
    url: 'https://webpetto.d1dc8nw7wsra2l.amplifyapp.com',
    title: 'Pilfarm',
    type: '랜딩페이지',
    duration: '12일 (기획 2일 / 디자인 4일 / 퍼블리싱 6일)',
    keywords: '#개성있는 #통통튀는 #깔끔한',
    color: '',
    purpose: 'asd',
  },
  {
    id: '5',
    img: '/portfolio.png',
    url: 'https://webpetto.d1u6bv97w93hxr.amplifyapp.com',
    title: 'Sclipse',
    type: '랜딩페이지',
    duration: '12일 (기획 2일 / 디자인 4일 / 퍼블리싱 6일)',
    keywords: '#개성있는 #통통튀는 #깔끔한',
    color: '',
    purpose: 'asd',
  },
  {
    id: '6',
    img: '/portfolio.png',
    url: 'https://webpetto.d3019aesm5q6ca.amplifyapp.com',
    title: 'Lumos',
    type: '랜딩페이지',
    duration: '12일 (기획 2일 / 디자인 4일 / 퍼블리싱 6일)',
    keywords: '#개성있는 #통통튀는 #깔끔한',
    color: '',
    purpose: 'asd',
  },
  {
    id: '7',
    img: '/portfolio.png',
    url: 'https://webpetto.d3p1ights4yfem.amplifyapp.com',
    title: 'Necta',
    type: '랜딩페이지',
    duration: '12일 (기획 2일 / 디자인 4일 / 퍼블리싱 6일)',
    keywords: '#개성있는 #통통튀는 #깔끔한',
    color: '',
    purpose: 'asd',
  },
];

export const ourWorkPaths = [
  { params: { id: '1' } },
  { params: { id: '2' } },
  { params: { id: '3' } },
  { params: { id: '4' } },
  { params: { id: '5' } },
  { params: { id: '6' } },
  { params: { id: '7' } },
];
